# name: Latest blog post workflow
# on:
#   schedule: # Run workflow automatically
#     - cron: '0 0 * * *' # Runs every hour, on the hour
#   workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
# permissions:
#   contents: write # To write the generated contents to the readme

# jobs:
#   update-readme-with-blog:
#     name: Update this repo's README with latest blog posts
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           max_post_count: "4"
#           feed_list: "https://medium.com/feed/@selcuk.san"

on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  blog:
    runs-on: ubuntu-latest
    name: Fetch and Generate Blog Posts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate
        uses: ErrorGamer2000/github-readme-blog-post-action@v1
        with:
          feed_urls: https://medium.com/feed/@selcuk.san
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save Generated Blog Posts
          skip_checkout: true
